name: Build and deploy code

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Running build command
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: ${{secrets.DEPLOYMENT_USERNAME}}
          key: ${{secrets.DEPLOYMENT_SSH_KEY}}
          passphrase: ${{secrets.DEPLOYMENT_SSH_KEY_PASSPHRASE}}
          script: |
            cd /home/${{secrets.DEPLOYMENT_USERNAME}}/zolza-hairstyles-web
            git reset --hard
            git pull
            npm install
            npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploying to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: ${{secrets.DEPLOYMENT_USERNAME}}
          key: ${{secrets.DEPLOYMENT_SSH_KEY}}
          passphrase: ${{secrets.DEPLOYMENT_SSH_KEY_PASSPHRASE}}
          script: |
            cd /home/${{secrets.DEPLOYMENT_USERNAME}}/zolza-hairstyles-web
            echo ${{secrets.DEPLOYMENT_PASSWORD}} | sudo -S cp -r dist /var/www/zolza-hairstyles.pl
