name: Build and deploy code

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Installing Node v.14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Installing dependencies
        run: npm install
      - name: Building application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Deploying to the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: ${{secrets.DEPLOYMENT_USERNAME}}
          password: ${{secrets.DEPLOYMENT_PASSWORD}}
          script: |
            cd ${{secrets.DEPLOYMENT_USERNAME}}/zolza_hairstyles
            git pull
            npm run build
            echo ${{secrets.DEPLOYMENT_PASSWORD}} | sudo -S cp dist /var/www/zolza_hairstyles/html/
